#!/usr/bin/env bash

set -euo pipefail

# Resolve paths from the script location so it works from any current directory.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

source "$REPO_DIR/scripts/lib/colours.sh"

CLAUDE_TARGET="$REPO_DIR/targets/claude/CLAUDE.md"
CODEX_TARGET="$REPO_DIR/targets/codex/AGENTS.md"

mkdir -p "$REPO_DIR/targets/claude" "$REPO_DIR/targets/codex"

# Shared files stay small and ordered so generated targets are deterministic.
write_shared_content() {
	cat "$REPO_DIR/shared/global-rules.md"
	printf '\n'
	cat "$REPO_DIR/shared/identity.md"
	printf '\n'
	cat "$REPO_DIR/shared/skills-policy.md"
	printf '\n'
	cat "$REPO_DIR/shared/file-discovery.md"
}

# Claude gets slash-command skill references and hook/settings notes.
write_claude_addendum() {
	cat <<'EOF'

## Global skills

Apply across all projects. See individual skills for detailed rules. Per-project `.claude/settings.json` can disable skills via `skillOverrides` — useful if a skill's tech (Vue, Swift) isn't used in that project.

- `/accessibility` — When building interfaces, WCAG AA baseline, accessible design
- `/agent-config` — When maintaining this shared Claude and Codex configuration repo
- `/agentic-engineering` — When building with Claude API, Anthropic SDK, or managed agents
- `/architecture-decision-records` — When documenting significant architectural decisions
- `/bash` — When writing shell scripts, bash config, patterns
- `/code-style` — When formatting code, covering naming, comments, arrays, objects
- `/dependencies` — When adding packages, what to choose, when to add
- `/e2e-testing` — When writing end-to-end tests with Playwright
- `/error-handling` — When validating input, graceful fallbacks, error handling
- `/readme` — When writing a README, structure, what to include/cut
- `/session-management` — When saving/resuming sessions, tracking multi-session work, token efficiency, goal-driven execution
- `/swift` — When writing Swift, style, SwiftUI patterns, concurrency
- `/swift-ui` — When writing/reviewing SwiftUI code, views, state management
- `/typescript` — When using TypeScript, type safety, escape hatches
- `/ui-copy` — When writing microcopy, buttons, errors, empty states, CTAs
- `/unit-testing` — When writing unit tests, Vitest, philosophy, what to skip
- `/vite-patterns` — When configuring vite.config.ts, Vite project patterns
- `/vue` — When writing Vue code, formatting, patterns, composables, components
- `/vue-project-stack` — When working in Vue + Bun + Vitest + Tailwind + Gitflow stack
- `/writing` — When writing prose/documentation, voice, tone, structure, style

## Claude-specific configuration

Claude Code loads this file from `~/.claude/CLAUDE.md`. Hooks and settings are Claude-only and live in `targets/claude/`.
EOF
}

# Codex gets discovery notes instead of Claude-only hook instructions.
write_codex_addendum() {
	cat <<'EOF'

## Codex-specific configuration

Codex loads this file from `~/.codex/AGENTS.md`. Project instructions are discovered by walking from the repository root to the current working directory for `AGENTS.override.md`, then `AGENTS.md`.

Skills are loaded from `~/.agents/skills/` at user scope. Codex relies on skill frontmatter descriptions for discovery, so each skill description keeps the `Use this skill when` phrase while also including action-led wording, file globs, and related-skill hints.

Codex hooks exist, but parity with Claude hooks is out of scope for this refactor. The shared skill descriptions carry the discovery weight for Codex.

Trust and project behaviour belong in `~/.codex/config.toml`; do not depend on unstable fallback filename settings for core behaviour.
EOF
}

# Regenerate both target files from the same shared source.
{
	printf '<!-- Generated by scripts/sync.sh — do not edit -->\n\n'
	printf '# Global Claude configuration\n\n'
	printf 'Baseline rules for all projects. Project-specific rules live in AGENTS.md.\n\n'
	printf '**Each project must have AGENTS.md in `.claude/`.** Copy from `.claude/templates/AGENTS.md.template` or create with: purpose, functionality, tech choices, architecture notes, gotchas. AGENTS.md lives in `.claude/AGENTS.md` within the project, not here.\n\n'
	write_shared_content
	write_claude_addendum
} > "$CLAUDE_TARGET"

{
	printf '<!-- Generated by scripts/sync.sh — do not edit -->\n\n'
	printf '# Global Codex configuration\n\n'
	printf 'Baseline rules for all projects. Project-specific rules live in AGENTS.md.\n\n'
	write_shared_content
	write_codex_addendum
} > "$CODEX_TARGET"

printf '%s✓%s synced %stargets/claude/CLAUDE.md%s\n' "$GREEN" "$RESET_COLOUR" "$PURPLE" "$RESET_COLOUR"
printf '%s✓%s synced %stargets/codex/AGENTS.md%s\n' "$GREEN" "$RESET_COLOUR" "$PURPLE" "$RESET_COLOUR"
